package com.example.galv.exame.handlers;

public enum UpdateFor {
    UPDATE_FOR_NEW_EXAMS,
    UPDATE_FOR_OLD_EXAMS,
    UPDATE_FOR_ALL,
    UPDATE_FOR_GOTO_EXAM_OPENING_FRAGMENT,
    UPDATE_FOR_GOTO_EXAM_MAIN_FRAGMENT,
    UPDATE_FOR_FINISH
}